@baseUrl=https://localhost:5149

GET {{baseUrl}}/odata/cabins


### 获取所有cabin id
GET {{baseUrl}}/odata/cabins?$count=true&$top=0

###
GET {{baseUrl}}/api/cabins/1




###
# DELETE {{baseUrl}}/api/cabins





### 获取所有 guest id
GET {{baseUrl}}/odata/guests?$select=id



### booking

GET {{baseUrl}}/odata/bookings?$count=true&$skip=0&$top=2



### expand booking with cabin and guest
GET {{baseUrl}}/odata/bookings?$expand=cabin,guest&$skip=0&$top=2&$count=true